---
title: "STAT456_Proj"
output: html_document
date: '2023-04-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(geosphere)
library(geodist)
library(scatterplot3d)
library(car)
```


```{r}
accident <- read.csv("distance.csv")
#dist_between_dist <- dist(accident$distance)
#plot(hclust(dist_between_dist))
```




```{r}
#hc <- as.dist(hc)
#hc1 <- hclust(hc, method = "complete")
#plot(hc1, cex = 0.6)
#rect.hclust(hc1, k = 3, border = 2:100)
#cut <- cutree(hc1, k=3)
#points(df_subset)
colors_drunk <- ifelse(accident$DRUNK_DR == "0", "black",
                       ifelse(accident$DRUNK_DR == "1", "red",
                              ifelse(accident$DRUNK_DR == "2", "blue", "green")))
scatterplot3d(accident$PERSONS, accident$VE_TOTAL, accident$FATALS, xlab = "Person Count", ylab = "Vehicle Count", zlab = "Fatalities", color = colors_drunk, ylim = c(0,20), angle = 75)
legend("topright", legend = c("0 Drunk Drivers", "1 Drunk Driver", "2 Drunk Drivers", "4 Drunk Drivers"), pch = 16, col = c("black", "red", "blue", "green"))
scatterplot3d(accident$LATITUDE, accident$LONGITUD, accident$FATALS, xlab = "Latitude", ylab = "Longitude", zlab = "Fatalities", ylim = c(-100, -70), color = ifelse(accident$RUR_URB == "1","black", "red"), angle = 60)
legend("topright", legend = c("Urban", "Rural"), pch = 16, col = c("black", "red"))
ggplot(accident, aes(x=DRUNK_DR)) +
  geom_bar(stat = "count", fill = "steelblue") +
  ggtitle("Frequency of Drunk Driving") +
  xlab("Drunk Driving") + 
  ylab("Occurences")
ggplot(accident, aes(x=FATALS)) +
  geom_bar(stat = "count", fill = "steelblue") +
  ggtitle("Frequency of Fatalities in Dataset") +
  xlab("Fatalities") + 
  ylab("Occurences")
ggplot(accident, aes(x=RUR_URB)) +
  geom_bar(stat = "count", fill = "steelblue") +
  ggtitle("Frequency of Rural vs. Urban") +
  xlab("Rural = 1, Urban = 2") + 
  ylab("Occurences")

```


``` {r}
dist_accidents <- read.csv("distance.csv", header = TRUE)
plot(dist_accidents$distance, dist_accidents$FATALS, col = colors_drunk, xlab = "Distance (km)", ylab = "Fatalities", main = "Distance from a Major city vs. Fatalities")
legend("topright", legend = c("0 Drunk Drivers", "1 Drunk Driver", "2 Drunk Drivers"), pch = 16, col = c("black", "red", "blue", "green"))
hist(dist_accidents$distance, freq = FALSE, xlab = "Distance (km)", main = "Density Histogram of Distance from Major City")
hist(dist_accidents$distance[dist_accidents$distance <= 300], freq = FALSE, xlab = "Distance (km)", main = "Density Histogram of Distance from Major City")

```


``` {r MDS}
accident$statefactor <- as.factor(accident$STATE)
new_levels <- c(1:51)
levels(accident$statefactor) <- new_levels
levels(accident$statefactor)
accident$statefactor <- as.integer(accident$statefactor)

top_month <- c()
for(i in 1:51) {
  state <- table(accident$MONTH[which(accident$statefactor == i)])
  max <- which(state == max(state))
  top_month <- c(top_month, max[1])
}
top_month
states <- levels(as.factor(accident$STATENAME))
states <- states[1:51]
region <- c(4, 0, 3, 4, 2, 2, 5, 4, 4, 4, 4, 0, 2, 1, 1, 1, 1, 4, 4, 5, 4, 5, 1, 1, 4, 1, 2, 1, 2, 5, 5, 3, 5, 4, 1, 1, 3, 2, 5, 5, 4, 1, 4, 3, 2, 5, 4, 2, 4, 1, 2) #0 is non continental, 1 is midwest, 2 is western, 3 is southwest, 4 is southeast, 5 is northeast
top_hour <- c()
for(i in 1:51) {
  state <- table(accident$HOUR[which(accident$statefactor == i)])
  max <- which(state == max(state))
  top_hour <- c(top_hour, max[1])
}
top_hour
top_hospmn <- c()
for(i in 1:51) {
  state <- table(accident$HOSP_MN[which(accident$statefactor == i)])
  max <- which(state == max(state))
  top_hospmn <- c(top_hospmn, max[1])
}
top_hospmn

avg_dist <- c()
for(i in 1:51) {
  state <- which(accident$statefactor == i)
  dists <- accident$distance[state]
  avg <- mean(dists)
  avg_dist <- c(avg_dist, avg)
}
avg_dist # Not using at the moment

mds_df <- data.frame(states, top_month, top_hour, top_hospmn, avg_dist, region)
mds_df <- mds_df[-20,]
dist_mat <- dist(c(mds_df$top_month, mds_df$top_hour, mds_df$top_hospmn))
mds <- cmdscale(dist_mat, k = 2)
plot(mds, col = mds_df$region + 1, main = "MDS on US Accident Data (Hour, State, Month, Minutes from Hospital)", xlab = "Dimension 1", ylab = "Dimension 2")
legend("topright", legend = c("Non-Continental", "Midwest", "West", "Southwest","Southeast", "Northeast"), pch = 16, col = c("black", "red", "green", "blue", "light blue", "magenta"))

```